language: node_js
node_js:
  - 10.0
before_deploy:
  - cd docs
  - npm install
  - npm run build
  - cp demo-small.mp4 demo.gif dist/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: docs/dist
  on:
    branch: master
